name: Newman run

on:
  push:
    branches:
      - main

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.3  # Certifique-se de usar versões estáveis
      - name: Create dir for report
        run: |
          mkdir testArtifacts
          
      #Config environement
      - name: Install Node
        uses: actions/setup-node@v4.0.2  # Define o Node.js
        
      - name: Install Newman
        run: |
          npm install -g newman
          npm install -g newman-report-htmlextra
          
      - name: Run Test
        run: newman run ServerRest.postman_collection.json -e ServerRest.postman_environment.json -r cli,htmlextra
        
      - name: Report
        uses: actions/upload-artifact@v4  # Certifique-se de usar a versão correta
        with:
          name: reports
          path: newman
