name: Newman run

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checar o código
      - uses: actions/checkout@v4.1.3  # Certifique-se de usar versões estáveis
      - name: Create dir for report
        run: |
          mkdir testArtifacts
          
      ## 2️⃣ Configurar Node.js (versão moderna)
      - name: Install Node
        uses: actions/setup-node@v4  # Define o Node.js
        with: 
          node-version: 20
          #cache: 'npm'

      # 3️⃣ Instalar Newman e Reporter (últimas versões)
      - name: Install Newman and dependencies
        run: |
          npm install -g newman@latest
          npm install -g newman-reporter-htmlextra@latest

      # (Opcional) 4️⃣ Audit de vulnerabilidades
      - name: Security audit
        run: npm audit --omit=dev || true
          
      - name: Run Test
        run: |
          npm set loglevel error
          newman run ServerRest.postman_collection.json -e ServerRest.postman_environment.json -r cli,htmlextra

      # 6️⃣ Publicar o relatório como artefato
      - name: Upload Newman HTML Report
        uses: actions/upload-artifact@v4  # Certifique-se de usar a versão correta
        with:
          name: newman-html-report
          path: ./reports/newman-report.html
